name: Build go package
on: 
  push:
    branches:   
     - 'release/v*' 
jobs:
  build_go_bear:
    name: CA for CICD
    runs-on: ubuntu-latest

    steps:
    - name: checkout your source
      uses: actions/checkout@v3
    - name: cancel norun
      run: |
      if [[ $(git log --format=%B -n 1 $GITHUB_SHA) == "#NORUN"* ]]; then
            echo "Commit message starts with #NORUN, skipping action."
            exit 1
          fi
    # - name: setup go 
    #   uses: actions/setup-go@v4
    #     with:
    #       go-version: '1.14'
    #       check-latest: true

    # - name: run golang
    #    run: go version

# -name: link Railway
#   run: 

