name: Build go package
on: 
  push:
    branches:   
     - 'release/v*' 
jobs:
  build_go_bear:
    runs-on: ubuntu-latest

steps:
- name: setup go 
   - uses: actions/setup-go@v4
    with:
      go-version: '1.14'
      check-latest: true
  - run: go run hello.go
- name: checkout your source
  uses: actions/checkout@v3
- name: build app
  run: dotnet build 
- name: run go
  run: go version
# -name: link Railway
#   run: 

