name: Build go package
on: 
  push:
    branches:   
     - 'release/v*' 
jobs:
  build_go_bear:
    if: "!startsWith(github.event.head_commit.message, '#NORUN')"
    name: CA for CICD
    runs-on: ubuntu-latest

    steps:
    - name: checkout your source
      uses: actions/checkout@v3
    - name: deploy railway  
      uses: bervProject/railway-deploy@main
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      with:
        service: "smelly-scarecrow"
    - name: Send payload to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*DipSA 56 CI/CD Submission*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Name:*  LIU JIAYI"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Email:*  e1112897@u.nus.edu"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Matriculation:*  A0269514X"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*  ${{vars.REPO}}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{vars.RAILWAY_URL}}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "emoji": true,
                      "text": "Go"
                    },
                    "url": "${{vars.RAILWAY_URL}}"
                  }
                }
              ]
            }
      env:
        SLACK_WEBHOOK_URL: ${{secrets.TEST_SUBMIT}}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK



    # - name: cancel norun
    #   run: |
    #     if [[ $(git log --format=%B -n 1 ${{ github.sha }}) == "#NORUN"* ]]; then
    #         echo "Commit message starts with #NORUN, skipping action."
    #         exit 1
    #       fi
    # - name: setup go 
    #   uses: actions/setup-go@v4
    #     with:
    #       go-version: '1.14'
    #       check-latest: true

    # - name: run golang
    #    run: go version

# -name: link Railway
#   run: 

